version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
       schedule:
          interval: 'weekly'
          day: 'monday'
      reviewers:
          - 'kylemcd'
  - package-ecosystem: npm
    directory: /
     schedule:
          interval: 'weekly'
          day: 'monday'
      reviewers:
          - 'kylemcd'
      
